# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCookiePetTreasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('cookie0001', '용사맛쿠키'), ('cookie0002', '딸기맛쿠키'), ('cookie0003', '소다맛쿠키'), ('pet0001', '반짝이볼'), ('pet0002', '공주의 장신구'), ('pet0003', '마법사전'), ('treasure0001', '방어막 버블건'), ('treasure0002', '곰젤리 아이스크림'), ('treasure0003', '미니 자석 로봇')], max_length=20)),
                ('amount', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookierun.Player')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
