# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0003_logaccess_logchest_logdailymission_logeventmission_logexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogCrystalGoldUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('crystal', '크리스탈'), ('gold', '골드')], max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('delta', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookierun.Player')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
