# Generated by Django 2.1.3 on 2018-11-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0004_logcrystalgoldusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cookie1st_id', models.IntegerField(default=-1)),
                ('cookie2nd_id', models.IntegerField(default=-1)),
                ('pet_id', models.IntegerField(default=-1)),
                ('treasure1st_id', models.IntegerField(default=-1)),
                ('treasure2nd_id', models.IntegerField(default=-1)),
                ('treasure3rd_id', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookierun.Player')),
            ],
            options={
                'ordering': ('score',),
            },
        ),
        migrations.CreateModel(
            name='LogGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('cookie1st_id', models.IntegerField(default=-1)),
                ('cookie2nd_id', models.IntegerField(default=-1)),
                ('pet_id', models.IntegerField(default=-1)),
                ('treasure1st_id', models.IntegerField(default=-1)),
                ('treasure2nd_id', models.IntegerField(default=-1)),
                ('treasure3rd_id', models.IntegerField(default=-1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookierun.Player')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.RemoveField(
            model_name='logchest',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='logeventmission',
            name='pname',
        ),
        migrations.RemoveField(
            model_name='logcookiepettreasure',
            name='types',
        ),
        migrations.RemoveField(
            model_name='logexperience',
            name='get_exp',
        ),
        migrations.RemoveField(
            model_name='logexperience',
            name='result_exp',
        ),
        migrations.RemoveField(
            model_name='logexperience',
            name='result_lv',
        ),
        migrations.AddField(
            model_name='logcookiepettreasure',
            name='equip_id',
            field=models.CharField(default='cookie0001', max_length=20),
        ),
        migrations.AddField(
            model_name='logcookiepettreasure',
            name='lv',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logdailymission',
            name='mission_quest_type',
            field=models.CharField(choices=[('OPTIONAL_QUEST', 'OPTIONAL_QUEST'), ('NOT_OPTIONAL_QUEST', 'NOT_OPTIONAL_QUEST')], default='OPTIONAL_QUEST', max_length=20),
        ),
        migrations.AddField(
            model_name='logdailymission',
            name='mission_reward_type',
            field=models.CharField(choices=[('STEP_BY_STEP_REWARD', 'STEP_BY_STEP_REWARD'), ('ONLY_FINAL_REWARD', 'ONLY_FINAL_REWARD')], default='STEP_BY_STEP_REWARD', max_length=20),
        ),
        migrations.AddField(
            model_name='logexperience',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logexperience',
            name='lv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logcookiepettreasure',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logcrystalgoldusage',
            name='types',
            field=models.CharField(choices=[('crystal', 'crystal'), ('gold', 'gold')], default='gold', max_length=20),
        ),
        migrations.DeleteModel(
            name='LogChest',
        ),
        migrations.DeleteModel(
            name='LogEventMission',
        ),
    ]
