# Generated by Django 2.1.3 on 2018-11-18 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0005_auto_20181118_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logbestscore',
            options={'ordering': ('-score',)},
        ),
    ]
