# Generated by Django 2.1.3 on 2018-11-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0006_auto_20181118_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbestscore',
            name='pname',
        ),
        migrations.DeleteModel(
            name='LogBestScore',
        ),
    ]
