# Generated by Django 2.1.3 on 2018-11-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0007_auto_20181118_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggame',
            name='id',
        ),
        migrations.AddField(
            model_name='loggame',
            name='gid',
            field=models.IntegerField(default=100000, primary_key=True, serialize=False),
        ),
    ]
