# Generated by Django 2.1.3 on 2018-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0008_auto_20181119_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggame',
            name='gid',
        ),
        migrations.AddField(
            model_name='loggame',
            name='id',
            field=models.AutoField(default=10000, primary_key=True, serialize=False),
        ),
    ]
