# Generated by Django 2.1.3 on 2018-11-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0010_auto_20181119_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogOpenChest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(default='gold_chest', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookierun.Player')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AddField(
            model_name='loggame',
            name='play_time',
            field=models.IntegerField(default=0),
        ),
    ]
