# Generated by Django 2.1.3 on 2018-11-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookierun', '0011_auto_20181122_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
